// Case generator for Djinn's Court Chaos.
// Each case is an absurd "crime" for the Plaintiff and Defendant teams to argue over.
// No AI needed here — pure template comedy.

const CHARGES = [
  { charge: "Stealing the last slice of pizza at the family cookout",
    detail: "The defendant claims 'finders keepers.' The plaintiff claims 'I literally paid for the whole pizza.'" },
  { charge: "Farting in a crowded elevator and blaming a child",
    detail: "Security footage is inconclusive. The child has an alibi — he was holding his nose before it happened." },
  { charge: "Eating someone's clearly-labeled leftovers from the work fridge",
    detail: "The container said 'DO NOT TOUCH' in three languages. The defendant says hunger is a universal language." },
  { charge: "Spoiling the ending of a show everyone else is still watching",
    detail: "The defendant posted it in the group chat at 2 AM. The plaintiff was only on episode 3." },
  { charge: "Taking 45 minutes in the only bathroom before a road trip",
    detail: "The plaintiff's bladder has filed a separate complaint. The defendant claims 'self-care is not a crime.'" },
  { charge: "Reheating fish in the office microwave",
    detail: "Three coworkers evacuated. The break room still smells like low tide. The defendant calls it 'meal prep.'" },
  { charge: "Backing into a parking spot way too slowly while everyone waits",
    detail: "Seven cars honked. One driver aged visibly. The defendant was 'just being careful.'" },
  { charge: "Talking through the entire movie at the theater",
    detail: "The plaintiff missed every plot twist. The defendant insists they were 'adding commentary.'" },
  { charge: "Using the last of the toilet paper and not replacing the roll",
    detail: "A cardboard tube was left as evidence. The defendant's fingerprints are all over this one." },
  { charge: "Leaving one sip of juice in the carton and putting it back",
    detail: "Forensics confirm: one (1) sip remained. The defendant calls it 'being considerate of the next person.'" },
  { charge: "Falling asleep on the couch during game night and snoring through the finals",
    detail: "The snoring was recorded at 82 decibels. The defendant claims they were 'resting their eyes strategically.'" },
  { charge: "Double-dipping the chip at the party",
    detail: "Witnesses counted three dips, one chip. The defendant argues the dip 'was basically theirs anyway.'" },
  { charge: "Sending a risky text to the wrong group chat",
    detail: "The message was meant for one person. It reached 47. Screenshots are now exhibits A through Z." },
  { charge: "Wearing socks with sandals to a wedding",
    detail: "The photographer has refused to release the photos. The defendant calls it 'comfort over convention.'" },
  { charge: "Clipping toenails in the living room",
    detail: "A toenail was recovered from the couch cushions. The defendant shows no remorse." },
  { charge: "Starting the group project the night before it's due",
    detail: "The plaintiff did 90% of the work. The defendant contributed a title slide and 'moral support.'" },
  { charge: "Blasting music at 6 AM on a Saturday",
    detail: "The whole street woke up. The defendant was 'just feeling the vibe.' The vibe is now a co-defendant." },
  { charge: "Borrowing the car and returning it on empty",
    detail: "The tank was bone dry. The defendant left an air freshener as compensation. The court is unimpressed." },
  { charge: "Licking the spoon and putting it back in the dip",
    detail: "Lab tests confirm saliva. The defendant claims 'taste-testing is a public service.'" },
  { charge: "Reading someone's texts over their shoulder",
    detail: "The defendant memorized the whole conversation. The plaintiff wants those memories subpoenaed." },
  { charge: "Hogging the aux cord and playing only their own playlist",
    detail: "Four hours. One genre. Zero skips allowed. The passengers have formed a support group." },
  { charge: "Finishing the ice cream and putting the empty carton back in the freezer",
    detail: "The plaintiff's scream was heard three houses away. The defendant calls it 'an innocent mistake.'" },
  { charge: "Leaving the shopping cart in the middle of the parking lot",
    detail: "It rolled into a BMW. The defendant was 'in a hurry.' Justice is never in a hurry." },
  { charge: "Snoring so loud the neighbors filed a noise complaint",
    detail: "Two noise complaints. One concerned citizen. The defendant's snore has its own zip code now." },
  { charge: "Dodging child support by claiming to be 'between blessings'",
    detail: "The defendant says the money is tied up in 'spiritual investments.' The plaintiff has receipts — and a baby that eats every single day." },
  { charge: "Paying child support in mixtapes instead of money",
    detail: "The defendant dropped off 14 burned CDs. The court does not accept SoundCloud links as currency." },
  { charge: "Claiming the kids as dependents while owing six months of support",
    detail: "The defendant filed taxes with total confidence. The plaintiff filed this case with total receipts." },
  { charge: "Borrowing $200 'until Friday' — it is now seven Fridays later",
    detail: "The defendant keeps saying 'I got you next week.' The plaintiff has started charging interest in the form of pure disrespect." },
  { charge: "Never paying back the Cash App loan with the pizza emoji memo",
    detail: "$75 sent, zero returned. The defendant claims the pizza emoji legally made it a gift." },
  { charge: "Owing everybody in the group chat and still ordering bottle service",
    detail: "The defendant popped bottles on Saturday night. The plaintiff sent the Venmo request on Sunday morning." },
  { charge: "Selling the plaintiff's PlayStation to cover a debt to somebody else",
    detail: "The defendant calls it 'redistributing assets.' The plaintiff calls it theft with extra steps." },
  { charge: "Smoking up the whole rotation without putting in a dime",
    detail: "The defendant hit it four times and passed nothing but excuses. The plaintiff kept the receipts and the roach." },
  { charge: "Smoking everybody's weed and then eating all the snacks",
    detail: "The defendant finished the stash AND the Hot Pockets. The plaintiff considers this a double homicide." },
  { charge: "Falling asleep on weed-watch and letting the bag go missing",
    detail: "The defendant was supposed to hold it. The defendant held a nap instead. The bag remains at large." },
  { charge: "Drinking the last of the Hennessy and refilling the bottle with iced tea",
    detail: "Lab tests confirm: 0% alcohol, 100% betrayal. The defendant claims it was 'a social experiment.'" },
  { charge: "Finishing the whole 12-pack and blaming the empty cans on 'the vibe'",
    detail: "Twelve cans entered. Zero explanations exited. The defendant has pled the fifth... of whiskey." },
  { charge: "Showing up to the cookout empty-handed and drinking everybody's cooler",
    detail: "The defendant brought 'good energy.' The plaintiff brought receipts for $87 worth of beer." },
  { charge: "Being the brokest one at the function with the most opinions",
    detail: "The defendant contributed zero dollars and seventeen hot takes. The plaintiff funded the entire night." },
  { charge: "Asking for a ride everywhere but never chipping in for gas",
    detail: "The defendant's legs work fine. The plaintiff's gas tank does not run on friendship." },
  { charge: "Eating at the restaurant and 'forgetting' their wallet every single time",
    detail: "Three dinners. Three forgotten wallets. The plaintiff now brings a separate check and a grudge." },
  { charge: "Cheating with the neighbor while the game was on",
    detail: "The defendant said they were 'just borrowing sugar.' The plaintiff found two phones and zero sugar." },
  { charge: "Getting caught because the side piece texted 'good morning' to the wrong number",
    detail: "The text went to the plaintiff. The defendant claims it was 'a motivational message for everybody.'" },
  { charge: "Liking every single photo on the ex's Instagram at 3 AM",
    detail: "Forty-seven likes. The defendant calls it 'an accident.' The plaintiff calls it Exhibits A through Z." },
  { charge: "The cousin dating the plaintiff's ex one week after the breakup",
    detail: "The defendant says 'she chose me.' The plaintiff says 'you chose violence.'" },
  { charge: "The brother 'just checking in' on the plaintiff's girlfriend every single day",
    detail: "Daily check-ins. Zero emergencies. The plaintiff has the call log printed, highlighted, and laminated." },
  { charge: "The uncle sliding into the plaintiff's girlfriend's DMs with 'hey big head'",
    detail: "Screenshots don't lie. The defendant claims his account was hacked — by thirst." },
  { charge: "Bringing the side piece to the same restaurant as the anniversary dinner",
    detail: "Same restaurant. Same night. Different table, same poor decisions. The waiter is now a sworn witness." },
  { charge: "Having a whole second family across town",
    detail: "Two households. One defendant. The plaintiff found out at the cookout when somebody yelled 'Dad!' twice." },
  { charge: "Cheating and blaming it on Mercury being in retrograde",
    detail: "The defendant cites astrology. The plaintiff cites the text messages, the hotel receipt, and common sense." },
  { charge: "The sister telling the plaintiff's girlfriend all his business",
    detail: "Family group chat leaks. The defendant says 'we're just close.' The plaintiff says 'you're just messy.'" },
  { charge: "Sneaking out to 'the store' for six hours with a full tank of gas",
    detail: "The tank came back empty. So did the excuses. The store was closed the entire time." },
  { charge: "Getting matching tattoos with somebody who is not the plaintiff",
    detail: "The defendant's arm says 'Forever.' The plaintiff's lawyer says 'perjury.'" },
];

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function makeCase() {
  const c = pick(CHARGES);
  return {
    title: "Case #" + (1000 + Math.floor(Math.random() * 9000)),
    charge: c.charge,
    detail: c.detail,
  };
}

module.exports = { makeCase };
